version: '3.6'

networks:
  internal-mesh:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.138.0/24

services:

  consul-mars:
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    command: agent -client 0.0.0.0 -bootstrap-expect 1  -config-file=/consul/config/config.json
    volumes:
      - ./consul/mars/config.json:/consul/config/config.json
      - ./consul/mars/data/consul-mars:/consul/data
    networks:
      internal-mesh:
        ipv4_address: 172.16.138.50

  consul-worker-mars1:
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -client 0.0.0.0  -config-file=/consul/config/config.json
    volumes:
      - ./consul/mars/config.json:/consul/config/config.json
      - ./consul/mars/data/consul-worker-mars1:/consul/data
    depends_on:
      - consul-mars
    networks:
      internal-mesh:
        ipv4_address: 172.16.138.51

  consul-worker-mars2:
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -client 0.0.0.0  -config-file=/consul/config/config.json
    volumes:
      - ./consul/mars/config.json:/consul/config/config.json
      - ./consul/mars/data/consul-worker-mars2:/consul/data
    depends_on:
      - consul-mars
    networks:
      internal-mesh:
        ipv4_address: 172.16.138.52

  vault-mars:
      image: 'vault'
      init: true
      command:
        - "sh"
        - "-c"
        - |
          set -ex
          export IP=$$(ip -o ro get $$(ip ro | awk '$$1 == "default" { print $$3 }') | awk '{print $$5}')
          export VAULT_API_ADDR="http://$${IP}:8200" VAULT_CLUSTER_ADDR="https://$${IP}:8201"
          exec vault server -config=/vault/config
      scale: 3
      environment:
        VAULT_ADDR: 'http://127.0.0.1:8200'
        VAULT_LOCAL_CONFIG: >-
          {
              "ui": true,
              "backend": {
                  "consul": {
                      "address": "consul-mars:8500",
                      "path": "vault",
                      "scheme": "http"
                  }
              },
              "default_lease_ttl": "168h",
              "listener": {
                  "tcp": {
                      "address": "0.0.0.0:8200",
                      "tls_disable": "1"
                  }
              },
              "max_lease_ttl": "720h"
          }
      cap_add:
        - IPC_LOCK
      networks:
        - internal-mesh
      depends_on:
        - consul-mars

  ################
  nginx: 
    image: nginx:latest
    container_name: nginx_vault
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    networks:
      - internal-mesh
    depends_on:
      - vault-mars

  consul-venus:
    build:
      context: ./consul
      dockerfile: Dockerfile
    ports:
      - 8600:8500
    command: agent -client 0.0.0.0  -bootstrap-expect 1  -config-file=/consul/config/config.json
    volumes:
      - ./consul/venus/config.json:/consul/config/config.json
      - ./consul/venus/data/consul-venus:/consul/data
    networks:
      internal-mesh:
        ipv4_address: 172.16.138.100

  consul-worker-venus1:
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -client 0.0.0.0  -config-file=/consul/config/config.json
    volumes:
      - ./consul/venus/config.json:/consul/config/config.json
      - ./consul/venus/data/consul-worker-venus1:/consul/data
    depends_on:
      - consul-venus
    networks:
      internal-mesh:
        ipv4_address: 172.16.138.101

  consul-worker-venus2:
    build:
      context: ./consul
      dockerfile: Dockerfile
    command: agent -client 0.0.0.0  -config-file=/consul/config/config.json
    volumes:
      - ./consul/venus/config.json:/consul/config/config.json
      - ./consul/venus/data/consul-worker-venus2:/consul/data  
    depends_on:
      - consul-venus
    networks:
      internal-mesh:
        ipv4_address: 172.16.138.102
    
  replicator: 
    build:
      context: ./replicator
      dockerfile: Dockerfile
    volumes:
      - ./replicator/data:/etc/replicator/
    networks:
      - internal-mesh
    depends_on:
      - vault-mars

